export const PORT = Number(process.env.PORT ?? 5000);

export const symbols = {
  ES: "ES=F",
  NQ: "NQ=F",
  YM: "YM=F",
  GOLD: "GC=F",
  DXY: "DX-Y.NYB",
  USOIL: "CL=F",
  VIX: "^VIX",
  US10Y: "^TNX",
};

export const dashboardAssets = ["ES", "NQ", "YM", "GOLD", "DXY", "USOIL"];

export const newsSources = [
  {
    id: "cnbc-top",
    name: "CNBC Top News",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    category: "market_news",
    enabled: true,
  },
  {
    id: "cnbc-finance",
    name: "CNBC Finance",
    url: "https://www.cnbc.com/id/10000664/device/rss/rss.html",
    category: "market_news",
    enabled: true,
  },
  {
    id: "cnbc-investing",
    name: "CNBC Investing",
    url: "https://www.cnbc.com/id/15839069/device/rss/rss.html",
    category: "market_news",
    enabled: true,
  },
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    url: "https://news.yahoo.com/rss/finance",
    category: "market_news",
    enabled: true,
  },
  {
    id: "fed-press",
    name: "Federal Reserve Press Releases",
    url: "https://www.federalreserve.gov/feeds/press_all.xml",
    category: "official_macro",
    enabled: true,
  },
  {
    id: "bls-latest",
    name: "BLS Latest Releases",
    url: "https://www.bls.gov/feed/bls_latest.rss",
    category: "official_macro",
    enabled: false,
  },
];

export const newsFeeds = newsSources
  .filter((source) => source.enabled)
  .map((source) => source.url);

export const assetRules = {
  ES: {
    positive: [
      "rate cut",
      "soft landing",
      "cooling inflation",
      "strong earnings",
      "stimulus",
      "risk-on",
      "disinflation",
      "dovish",
      "beat estimates",
    ],
    negative: [
      "hot inflation",
      "rate hike",
      "hawkish",
      "recession",
      "tariff",
      "geopolitics",
      "war",
      "selloff",
      "risk-off",
      "bank stress",
      "higher yields",
      "downgrade",
      "miss estimates",
    ],
  },

  NQ: {
    positive: [
      "ai boom",
      "chip demand",
      "strong earnings",
      "rate cut",
      "cooling inflation",
      "risk-on",
      "dovish",
      "tech rally",
    ],
    negative: [
      "higher yields",
      "hawkish",
      "antitrust",
      "tech selloff",
      "tariff",
      "chip restrictions",
      "export ban",
      "risk-off",
      "hot inflation",
      "tightening financial conditions",
    ],
  },

  YM: {
    positive: [
      "industrial rebound",
      "soft landing",
      "strong payrolls",
      "stimulus",
      "risk-on",
      "strong manufacturing",
    ],
    negative: [
      "recession",
      "tariff",
      "geopolitics",
      "manufacturing slowdown",
      "higher input costs",
      "risk-off",
      "weak payrolls",
    ],
  },

  GOLD: {
    positive: [
      "geopolitics",
      "war",
      "risk-off",
      "bank stress",
      "recession",
      "dovish",
      "rate cut",
      "safe haven",
      "usd weakness",
    ],
    negative: [
      "higher yields",
      "hawkish",
      "usd strength",
      "strong dollar",
      "risk-on",
      "strong real yields",
    ],
  },

  DXY: {
    positive: [
      "hawkish",
      "higher yields",
      "rate hike",
      "strong payrolls",
      "hot inflation",
      "safe haven",
      "risk-off",
    ],
    negative: [
      "dovish",
      "rate cut",
      "cooling inflation",
      "usd weakness",
      "disinflation",
      "soft payrolls",
    ],
  },

  USOIL: {
    positive: [
      "supply cut",
      "opec cut",
      "middle east tensions",
      "inventory draw",
      "geopolitics",
      "strong demand",
    ],
    negative: [
      "inventory build",
      "weak demand",
      "recession",
      "slowdown",
      "output increase",
      "oversupply",
    ],
  },
};

export const impactCategoryRules = [
  {
    category: "CENTRAL_BANK",
    weight: 3.2,
    keywords: [
      "fed",
      "fomc",
      "powell",
      "ecb",
      "boj",
      "boe",
      "rate cut",
      "rate hike",
      "hawkish",
      "dovish",
      "monetary policy",
    ],
  },
  {
    category: "INFLATION",
    weight: 3,
    keywords: [
      "cpi",
      "pce",
      "inflation",
      "core inflation",
      "prices rose",
      "hot inflation",
      "cooling inflation",
      "disinflation",
    ],
  },
  {
    category: "LABOR",
    weight: 2.6,
    keywords: [
      "payroll",
      "nfp",
      "jobs",
      "labor market",
      "unemployment",
      "wages",
      "strong payrolls",
      "weak payrolls",
    ],
  },
  {
    category: "GEOPOLITICS",
    weight: 3,
    keywords: [
      "war",
      "geopolitics",
      "missile",
      "attack",
      "military",
      "sanctions",
      "conflict",
      "middle east tensions",
      "invasion",
    ],
  },
  {
    category: "TRADE_POLICY",
    weight: 2.8,
    keywords: [
      "tariff",
      "trade war",
      "export ban",
      "chip restrictions",
      "restrictions",
      "sanctions",
      "trade policy",
    ],
  },
  {
    category: "ENERGY",
    weight: 2.7,
    keywords: [
      "oil",
      "opec",
      "inventory draw",
      "inventory build",
      "supply cut",
      "output increase",
      "oversupply",
      "energy prices",
    ],
  },
  {
    category: "BANKING_STRESS",
    weight: 2.8,
    keywords: [
      "bank stress",
      "banking crisis",
      "liquidity stress",
      "credit stress",
      "downgrade",
      "financial stability",
    ],
  },
  {
    category: "EARNINGS",
    weight: 1.7,
    keywords: [
      "earnings",
      "beat estimates",
      "miss estimates",
      "guidance",
      "revenue",
      "profit",
    ],
  },
];

export const urgencyKeywords = [
  "breaking",
  "unexpected",
  "surprise",
  "urgent",
  "escalation",
  "hotter than expected",
  "cooler than expected",
  "shock",
  "warning",
];

export const positiveSentimentPatterns = [
  "rate cut",
  "soft landing",
  "cooling inflation",
  "strong earnings",
  "stimulus",
  "risk-on",
  "disinflation",
  "dovish",
  "beat estimates",
  "ai boom",
  "chip demand",
  "tech rally",
  "industrial rebound",
  "strong payrolls",
  "safe haven",
  "usd weakness",
  "supply cut",
  "opec cut",
  "inventory draw",
  "strong demand",
];

export const negativeSentimentPatterns = [
  "hot inflation",
  "rate hike",
  "hawkish",
  "recession",
  "tariff",
  "geopolitics",
  "war",
  "selloff",
  "risk-off",
  "bank stress",
  "higher yields",
  "downgrade",
  "miss estimates",
  "tech selloff",
  "chip restrictions",
  "export ban",
  "tightening financial conditions",
  "manufacturing slowdown",
  "higher input costs",
  "weak payrolls",
  "usd strength",
  "strong dollar",
  "strong real yields",
  "inventory build",
  "weak demand",
  "slowdown",
  "output increase",
  "oversupply",
];

export const sentimentSourceWeights = {
  CNBC: 1,
  Reuters: 1.2,
  default: 0.9,
};

export const assetRelevanceRules = {
  ES: [
    "economy",
    "inflation",
    "fed",
    "fomc",
    "rates",
    "yield",
    "tariff",
    "geopolitics",
    "war",
    "recession",
    "risk-on",
    "risk-off",
    "earnings",
    "stimulus",
    "soft landing",
    "payroll",
    "cpi",
    "pce",
  ],
  NQ: [
    "tech",
    "ai",
    "chip",
    "nasdaq",
    "yield",
    "rates",
    "fed",
    "fomc",
    "tariff",
    "export ban",
    "antitrust",
    "risk-on",
    "risk-off",
    "earnings",
    "inflation",
    "cpi",
  ],
  YM: [
    "industrial",
    "manufacturing",
    "payroll",
    "economy",
    "recession",
    "tariff",
    "war",
    "stimulus",
    "soft landing",
    "input costs",
    "growth",
  ],
  GOLD: [
    "gold",
    "safe haven",
    "geopolitics",
    "war",
    "risk-off",
    "dollar",
    "usd",
    "yield",
    "real yields",
    "fed",
    "rate cut",
    "recession",
  ],
  DXY: [
    "dollar",
    "usd",
    "fed",
    "hawkish",
    "dovish",
    "yield",
    "rates",
    "safe haven",
    "risk-off",
    "inflation",
    "payroll",
    "cpi",
    "pce",
  ],
  USOIL: [
    "oil",
    "opec",
    "inventory",
    "supply",
    "output",
    "middle east",
    "geopolitics",
    "war",
    "demand",
    "recession",
    "slowdown",
    "oversupply",
  ],
};

export const calendarImpactWeights = {
  white: 0,
  yellow: 0.5,
  orange: 1,
  red: 2,
};
