import { symbols } from "./constants.js";

export const flowAssets = [
  {
    id: "ES",
    displayName: "S&P 500 Futures",
    assetClass: "futures",
    provider: "yahoo",
    providerSymbol: symbols.ES,
    role: "core_equity_index",
    relatedCoreAssets: ["ES", "NQ", "YM"],
    riskBucket: "risk_assets",
  },
  {
    id: "NQ",
    displayName: "Nasdaq Futures",
    assetClass: "futures",
    provider: "yahoo",
    providerSymbol: symbols.NQ,
    role: "core_tech_index",
    relatedCoreAssets: ["NQ", "ES"],
    riskBucket: "tech_risk",
  },
  {
    id: "YM",
    displayName: "Dow Futures",
    assetClass: "futures",
    provider: "yahoo",
    providerSymbol: symbols.YM,
    role: "core_industrial_index",
    relatedCoreAssets: ["YM", "ES"],
    riskBucket: "industrial_risk",
  },
  {
    id: "GOLD",
    displayName: "Gold Futures",
    assetClass: "metals",
    provider: "yahoo",
    providerSymbol: symbols.GOLD,
    role: "core_metals",
    relatedCoreAssets: ["GOLD", "DXY", "US10Y"],
    riskBucket: "safe_haven",
  },
  {
    id: "DXY",
    displayName: "US Dollar Index",
    assetClass: "indices",
    provider: "yahoo",
    providerSymbol: symbols.DXY,
    role: "core_dollar",
    relatedCoreAssets: ["DXY", "GOLD", "ES", "NQ"],
    riskBucket: "dollar",
  },
  {
    id: "USOIL",
    displayName: "US Oil",
    assetClass: "futures",
    provider: "yahoo",
    providerSymbol: symbols.USOIL,
    role: "core_energy",
    relatedCoreAssets: ["USOIL", "ES", "NQ"],
    riskBucket: "energy",
  },
  {
    id: "VIX",
    displayName: "CBOE Volatility Index",
    assetClass: "indices",
    provider: "yahoo",
    providerSymbol: symbols.VIX,
    role: "volatility_confirming_proxy",
    relatedCoreAssets: ["ES", "NQ", "YM"],
    riskBucket: "volatility",
  },
  {
    id: "US10Y",
    displayName: "US 10Y Yield",
    assetClass: "rates",
    provider: "yahoo",
    providerSymbol: symbols.US10Y,
    role: "rates_proxy",
    relatedCoreAssets: ["US10Y", "DXY", "NQ", "GOLD"],
    riskBucket: "rates",
  },
  {
    id: "SPY",
    displayName: "SPDR S&P 500 ETF",
    assetClass: "etfs",
    provider: "yahoo",
    providerSymbol: "SPY",
    role: "equity_etf_confirmation",
    relatedCoreAssets: ["ES"],
    riskBucket: "risk_assets",
  },
  {
    id: "QQQ",
    displayName: "Invesco QQQ Trust",
    assetClass: "etfs",
    provider: "yahoo",
    providerSymbol: "QQQ",
    role: "tech_etf_confirmation",
    relatedCoreAssets: ["NQ"],
    riskBucket: "tech_risk",
  },
  {
    id: "DIA",
    displayName: "SPDR Dow Jones Industrial Average ETF",
    assetClass: "etfs",
    provider: "yahoo",
    providerSymbol: "DIA",
    role: "industrial_etf_confirmation",
    relatedCoreAssets: ["YM"],
    riskBucket: "industrial_risk",
  },
  {
    id: "GLD",
    displayName: "SPDR Gold Shares",
    assetClass: "etfs",
    provider: "yahoo",
    providerSymbol: "GLD",
    role: "gold_etf_confirmation",
    relatedCoreAssets: ["GOLD"],
    riskBucket: "safe_haven",
  },
  {
    id: "USO",
    displayName: "United States Oil Fund",
    assetClass: "etfs",
    provider: "yahoo",
    providerSymbol: "USO",
    role: "oil_etf_confirmation",
    relatedCoreAssets: ["USOIL"],
    riskBucket: "energy",
  },
  {
    id: "UUP",
    displayName: "Invesco DB US Dollar Index Bullish Fund",
    assetClass: "etfs",
    provider: "yahoo",
    providerSymbol: "UUP",
    role: "dollar_etf_confirmation",
    relatedCoreAssets: ["DXY"],
    riskBucket: "dollar",
  },
  {
    id: "IWM",
    displayName: "iShares Russell 2000 ETF",
    assetClass: "etfs",
    provider: "yahoo",
    providerSymbol: "IWM",
    role: "small_cap_risk_confirmation",
    relatedCoreAssets: ["ES", "YM"],
    riskBucket: "risk_assets",
  },
  {
    id: "COPPER",
    displayName: "Copper Futures",
    assetClass: "metals",
    provider: "yahoo",
    providerSymbol: "HG=F",
    role: "growth_metals_proxy",
    relatedCoreAssets: ["ES", "USOIL", "GOLD"],
    riskBucket: "industrial_risk",
  },
  {
    id: "EURUSD",
    displayName: "EUR/USD",
    assetClass: "forex",
    provider: "yahoo",
    providerSymbol: "EURUSD=X",
    role: "dollar_fx_cross",
    relatedCoreAssets: ["DXY", "GOLD"],
    riskBucket: "dollar",
  },
  {
    id: "USDJPY",
    displayName: "USD/JPY",
    assetClass: "forex",
    provider: "yahoo",
    providerSymbol: "USDJPY=X",
    role: "rates_fx_cross",
    relatedCoreAssets: ["DXY", "US10Y", "GOLD"],
    riskBucket: "rates",
  },
];

export const coreFlowAssets = ["ES", "NQ", "YM", "GOLD", "DXY", "USOIL"];
