export const localSymbolUniverse = [
  { symbol: "AAPL", displayName: "Apple Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "AAPL" },
  { symbol: "ABBV", displayName: "AbbVie Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "ABBV" },
  { symbol: "ABT", displayName: "Abbott Laboratories", assetClass: "stocks", provider: "yahoo", providerSymbol: "ABT" },
  { symbol: "ACN", displayName: "Accenture plc", assetClass: "stocks", provider: "yahoo", providerSymbol: "ACN" },
  { symbol: "ADBE", displayName: "Adobe Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "ADBE" },
  { symbol: "AMD", displayName: "Advanced Micro Devices Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "AMD" },
  { symbol: "AMZN", displayName: "Amazon.com Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "AMZN" },
  { symbol: "BA", displayName: "Boeing Co.", assetClass: "stocks", provider: "yahoo", providerSymbol: "BA" },
  { symbol: "BAC", displayName: "Bank of America Corp.", assetClass: "stocks", provider: "yahoo", providerSymbol: "BAC" },
  { symbol: "BRK.B", displayName: "Berkshire Hathaway Inc. Class B", assetClass: "stocks", provider: "yahoo", providerSymbol: "BRK-B" },
  { symbol: "COST", displayName: "Costco Wholesale Corp.", assetClass: "stocks", provider: "yahoo", providerSymbol: "COST" },
  { symbol: "CRM", displayName: "Salesforce Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "CRM" },
  { symbol: "CSCO", displayName: "Cisco Systems Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "CSCO" },
  { symbol: "DIA", displayName: "SPDR Dow Jones Industrial Average ETF", assetClass: "etfs", provider: "yahoo", providerSymbol: "DIA" },
  { symbol: "DIS", displayName: "Walt Disney Co.", assetClass: "stocks", provider: "yahoo", providerSymbol: "DIS" },
  { symbol: "GOOG", displayName: "Alphabet Inc. Class C", assetClass: "stocks", provider: "yahoo", providerSymbol: "GOOG" },
  { symbol: "GOOGL", displayName: "Alphabet Inc. Class A", assetClass: "stocks", provider: "yahoo", providerSymbol: "GOOGL" },
  { symbol: "GS", displayName: "Goldman Sachs Group Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "GS" },
  { symbol: "IBM", displayName: "International Business Machines Corp.", assetClass: "stocks", provider: "yahoo", providerSymbol: "IBM" },
  { symbol: "INTC", displayName: "Intel Corp.", assetClass: "stocks", provider: "yahoo", providerSymbol: "INTC" },
  { symbol: "IWM", displayName: "iShares Russell 2000 ETF", assetClass: "etfs", provider: "yahoo", providerSymbol: "IWM" },
  { symbol: "JPM", displayName: "JPMorgan Chase & Co.", assetClass: "stocks", provider: "yahoo", providerSymbol: "JPM" },
  { symbol: "KO", displayName: "Coca-Cola Co.", assetClass: "stocks", provider: "yahoo", providerSymbol: "KO" },
  { symbol: "META", displayName: "Meta Platforms Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "META" },
  { symbol: "MSFT", displayName: "Microsoft Corp.", assetClass: "stocks", provider: "yahoo", providerSymbol: "MSFT" },
  { symbol: "NFLX", displayName: "Netflix Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "NFLX" },
  { symbol: "NVDA", displayName: "NVIDIA Corp.", assetClass: "stocks", provider: "yahoo", providerSymbol: "NVDA" },
  { symbol: "ORCL", displayName: "Oracle Corp.", assetClass: "stocks", provider: "yahoo", providerSymbol: "ORCL" },
  { symbol: "PLTR", displayName: "Palantir Technologies Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "PLTR" },
  { symbol: "PYPL", displayName: "PayPal Holdings Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "PYPL" },
  { symbol: "QQQ", displayName: "Invesco QQQ Trust", assetClass: "etfs", provider: "yahoo", providerSymbol: "QQQ" },
  { symbol: "SPY", displayName: "SPDR S&P 500 ETF Trust", assetClass: "etfs", provider: "yahoo", providerSymbol: "SPY" },
  { symbol: "TSLA", displayName: "Tesla Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "TSLA" },
  { symbol: "UUP", displayName: "Invesco DB US Dollar Index Bullish Fund", assetClass: "etfs", provider: "yahoo", providerSymbol: "UUP" },
  { symbol: "V", displayName: "Visa Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "V" },
  { symbol: "WMT", displayName: "Walmart Inc.", assetClass: "stocks", provider: "yahoo", providerSymbol: "WMT" },
  { symbol: "XOM", displayName: "Exxon Mobil Corp.", assetClass: "stocks", provider: "yahoo", providerSymbol: "XOM" },
];
